# Login shells

[ -s "${CONFIG_HOME}/shell/platform.before.zprofile" ] && source "${CONFIG_HOME}/shell/platform.before.zprofile"

eval "$(mise activate zsh --shims)"

[ -s "${CONFIG_HOME}/shell/platform.zprofile" ] && source "${CONFIG_HOME}/shell/platform.zprofile"
