# Always sourced

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export LANG=en_US.UTF-8
export EDITOR=nvim
export MANPAGER="nvim +Man!"
export GPG_TTY=$(tty)

export PATH="$HOME/.local/bin:$PATH"