[settings]
system_packages.managers = ["pacman"]

[bootstrap.packages]
"pacman:base-devel" = "latest"
"pacman:git" = "latest"
"pacman:zoxide" = "latest"
"pacman:eza" = "latest"
"pacman:ripgrep" = "latest"
"pacman:fd" = "latest"
"pacman:bat" = "latest"
"pacman:jq" = "latest"
"pacman:fzf" = "latest"
"pacman:mise" = "latest"
"pacman:usage" = "latest"
"pacman:fastfetch" = "latest"
"pacman:dua-cli" = "latest"
"pacman:neovim" = "latest"
"pacman:nodejs" = "latest"
"pacman:npm" = "latest"
"pacman:python" = "latest"
"pacman:rustup" = "latest"
"pacman:ttf-iosevka-nerd" = "latest"

[dotfiles]
"~/.config/**/platform*" = { source = "linux/config/**/platform*" }

[vars]
aur_packages = """
herdr-bin
rtk-bin
pi-coding-agent-bin
"""

[tasks.os-bootstrap]
description = "Install Arch AUR packages"
hide = true
run = "{{ cwd | quote }}/scripts/install-aur-packages.sh"
env = { AUR_PACKAGES = "{{ vars.aur_packages }}" }
