[general]
live_config_reload = true
# Color theme
import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[window]
title = "ForAeons"
dimensions = { columns = 120, lines = 36 }
decorations = "full"
opacity = 0.8
blur = true
startup_mode = "Windowed"
dynamic_padding = true

[cursor]
style.blinking = "Always"
blink_timeout = 0

[font]
size = 18
normal = { "family" = "Iosevka Nerd Font Mono", style = "Regular" }
bold = { "family" = "Iosevka Nerd Font Mono", style = "Bold" }
italic = { "family" = "Iosevka Nerd Font Mono", style = "Normal Italic" }
bold_italic = { "family" = "Iosevka Nerd Font Mono", style = "Bold Italic" }
